name: stiky
description: "Stiky Flutter app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  go_router: ^14.8.1
    # Управление состоянием
  bloc: ^9.2.0 # Бизнес-логика приложения (паттерн BLoC)
  flutter_bloc: ^9.1.1 # Виджеты для связи BLoC с интерфейсом

  flutter_svg: ^2.2.3 # Отображение SVG-картинок и иконок
  cached_network_image: ^3.4.1 # Загрузка и кэширование картинок из интернета
  flutter_animate: ^4.5.2 # Простые и красивые анимации для виджетов
  gap: ^3.0.1 # Виджет-отступ — замена SizedBox(height: 16) на Gap(16)
  logger: ^2.6.2
  equatable: ^2.0.8 # Удобное сравнение объектов (нужно для BLoC-состояний)
  intl: ^0.20.2 # Форматирование дат, чисел и валют
  flutter_dotenv: ^6.0.0 # Чтение секретов и настроек из .env файла
  shared_preferences: ^2.5.4 # Локальное хранилище (сохранить тему, язык, токен)
  connectivity_plus: ^7.0.0 # Проверка интернет-соединения
  url_launcher: ^6.3.2 # Открытие ссылок, email и телефона из приложения
  image_picker: ^1.2.1 # Выбор фото из галереи или камеры

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
    # Генерация иконки и сплэш-экрана
  flutter_native_splash: ^2.4.7 # Экран загрузки при запуске приложения
  flutter_launcher_icons: ^0.14.4 # Генерация иконки приложения для Android и iOS

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  # ── App Icon ────────────────────────────────────
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon_1024.png"           # Android обычная иконка
  adaptive_icon_foreground: "assets/icons/adaptive_icon_foreground_1024.png"
  adaptive_icon_background: "#101010"
  ios_image_path: "assets/icons/app_icon_ios_1024.png"    # iOS (без альфы)
  min_sdk_android: 21
 
# ── Native Splash ───────────────────────────────
flutter_native_splash:
  color: "#101010"
  image: "assets/icons/splash_logo_1152.png"
  android_12:
    color: "#101010"
    image: "assets/icons/splash_logo_1152.png"
  ios: true
  android: true
